blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/whitedoeinn/wdi-workflows/discussions
    about: For questions or discussions, use GitHub Discussions instead of issues.
